openapi: 3.0.3
info:
  title: Messages API
  description: API endpoints for sending messages and streaming AI responses
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: Local development server

security:
  - BearerAuth: []

paths:
  /api/{user_id}/conversations/{conversation_id}/messages:
    post:
      summary: Send message to AI agent (with streaming response)
      description: Send a user message to the AI agent and receive a streamed response via Server-Sent Events
      operationId: sendMessage
      tags:
        - Messages
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  minLength: 1
                  maxLength: 100000
                  description: User message content
      responses:
        '200':
          description: Streaming response from AI agent
          content:
            text/event-stream:
              schema:
                type: string
                description: |
                  Server-Sent Events stream with the following event types:
                  - data: {chunk: "text"} - AI response chunks
                  - data: {done: true} - Stream completion signal
                  - data: {error: "message"} - Error occurred
              example: |
                data: {"chunk": "I've created a task"}
                data: {"chunk": " for you"}
                data: {"done": true}
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Conversation not found
        '500':
          description: Internal server error

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
